import os

## app1
# APP1_CONSUMER_KEY=os.environ.get('APP1_CONSUMER_KEY')
# APP1_CONSUMER_SECRET=os.environ.get('APP1_CONSUMER_SECRET')

## app2
APP2_CONSUMER_KEY=os.environ.get('APP2_CONSUMER_KEY')
APP2_CONSUMER_SECRET=os.environ.get('APP2_CONSUMER_SECRET')

## app3
APP3_CONSUMER_KEY=os.environ.get('APP2_CONSUMER_KEY')
APP3_CONSUMER_SECRET=os.environ.get('APP2_CONSUMER_SECRET')
